apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-deployment
  labels:
    app: node-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
      - name: node-hello-container
        image: {{ .Values.image }}
        ports:
        - containerPort: 3000